from .._common.error import Error

class CreditError(Error):
    
    INPUT_ERROR_CODE = 100
    INPUT_ERROR_MSG = 'INPUT ERROR'
    
    CARD_NUMBER_ERROR_CODE = 200
    CARD_NUMBER_ERROR_MSG = 'CARD NUMBER ERROR'
    
    CARD_ADD_ERROR_CODE = 300
    CARD_ADD_ERROR_MSG = 'CARD ADD ERROR'
    
    CARD_CHARGE_ERROR_CODE = 400
    CARD_CHARGE_ERROR_MSG = 'CARD CHARGE ERROR'
    
    CARD_CREDIT_ERROR_CODE = 500
    CARD_CREDIT_ERROR_MSG = 'CARD CREDIT ERROR'